/*
 * Memory Management.
 *
 * Source: "Operating System Notes.pdf" pp.37-47, "Os.pdf" pp.9-11, 20.
 *
 * THE ADDRESS TRANSLATION EXAMPLE IN THE NOTES DOES NOT ADD UP.
 *
 * `Os.pdf` p10 states a 14-bit logical address with 1 KB pages — which gives a
 * 4-bit page number and a 10-bit offset — and then splits 0x2AF3 as though it
 * were 16 bits, labelling a 12-bit field "offset (10-bit)". Its conclusion
 * (page 2 → frame 5) only follows if the address is 0x0AF3.
 *
 * The example is repaired rather than replaced: same page table, same frame,
 * same idea, one corrected address. `Os.pdf` p20's second paging question is
 * simply wrong arithmetic — 3500 with 1 KB pages gives offset 428, not 452.
 */

export default {
  id: "memory",
  name: "Memory Management",
  importance: "high",
  icon: "package",
  blurb:
    "Where a process's memory actually lives, how a logical address becomes a physical one, and why memory ends up full of holes.",
  source: "Operating System Notes pp.37-47 · Os.pdf pp.9-11, 20",

  questions: [
    {
      id: "os-mem-01",
      subtopic: "Basics",
      type: "conceptual",
      importance: "med",
      question: "What is the memory hierarchy?",
      short:
        "Registers, cache, RAM, SSD, disk — faster, smaller and dearer at the top; each level caches the one below.",
      answer: [
        { diagram: "memory-hierarchy" },
        {
          p: "Every level trades speed against cost per byte. You cannot have a terabyte of register-speed memory, so systems build a pyramid and rely on **locality** — the observation that programs reuse recently used data and nearby data — to make the fast levels hit most of the time.",
        },
        {
          note: "Look at the gaps: RAM is roughly 100× slower than L1, and a disk is roughly 100,000× slower than RAM. That last gap is the entire justification for virtual memory being designed the way it is.",
        },
      ],
      tags: ["memory hierarchy", "locality", "cache"],
    },
    {
      id: "os-mem-02",
      subtopic: "Addresses",
      type: "comparison",
      importance: "high",
      question: "Logical address vs physical address, and what is the MMU?",
      short:
        "The CPU generates logical addresses; the MMU translates them to physical ones. Programs never see a physical address.",
      answer: [
        {
          table: {
            head: ["", "Logical (virtual) address", "Physical address"],
            rows: [
              ["Generated by", "The CPU, during execution", "The MMU, after translation"],
              ["Visible to", "The program", "Hardware only"],
              ["Lives in", "The logical address space", "Actual RAM"],
              ["Needs translation", "Yes — via the page table", "No, it is the real thing"],
            ],
          },
        },
        {
          p: "The **Memory Management Unit** is hardware that sits between the CPU and the memory bus. It does four things:",
        },
        {
          ul: [
            "**Address translation** — logical → physical, on every single memory access.",
            "**Memory protection** — a process cannot name an address outside its own space, because the translation would fail.",
            "**Access control** — read, write and execute permissions per page.",
            "**Paging and segmentation support**.",
          ],
        },
        {
          note: "Protection here is a consequence of translation, not a separate check. A process literally cannot express another process's physical address, because its addresses are interpreted through its own page table.",
        },
      ],
      tags: ["mmu", "logical address", "physical address"],
    },
    {
      id: "os-mem-03",
      subtopic: "Fragmentation",
      type: "comparison",
      importance: "high",
      question: "Internal vs external fragmentation?",
      short:
        "Internal: wasted space *inside* an allocated block. External: enough total free space, but scattered in pieces too small to use.",
      answer: [
        {
          table: {
            head: ["", "Internal", "External"],
            rows: [
              ["Where the waste is", "Inside an allocated block", "Between allocated blocks"],
              ["Cause", "The block is bigger than what was asked for", "Allocation and freeing leaves gaps"],
              ["Example", "A process gets 8 KB and uses 6 KB — 2 KB wasted", "100 MB free in small chunks; a 20 MB process cannot fit"],
              ["Occurs in", "Fixed partitioning, paging", "Variable partitioning, segmentation"],
              ["Fix", "Smaller allocation units", "Compaction, or paging"],
            ],
          },
        },
        {
          note: "**Paging eliminates external fragmentation and creates internal fragmentation instead** — a process's last page is rarely exactly full, wasting on average half a page. That trade is the whole reason paging won.",
        },
      ],
      tip: "The one-liner: internal is waste you were given, external is waste you cannot reach.",
      tags: ["fragmentation", "internal", "external"],
    },
    {
      id: "os-mem-04",
      subtopic: "Contiguous allocation",
      type: "comparison",
      importance: "med",
      question: "Fixed vs variable partitioning?",
      short:
        "Fixed: partitions set at boot, causing internal fragmentation. Variable: sized to the process, causing external fragmentation.",
      answer: [
        {
          table: {
            head: ["", "Fixed (MFT)", "Variable (MVT)"],
            rows: [
              ["Partitions", "Set at system startup", "Created at runtime, sized to the process"],
              ["Degree of multiprogramming", "Fixed", "Variable"],
              ["Internal fragmentation", "Yes", "No"],
              ["External fragmentation", "No", "Yes"],
              ["Largest process", "Limited by the largest partition", "Limited by the largest free hole"],
              ["Complexity", "Simple", "Needs a free-list and compaction"],
            ],
          },
        },
        {
          p: "**Compaction** is the fix for external fragmentation under variable partitioning: shuffle all the allocated blocks to one end so the free space becomes one large hole. It is correct and it is expensive — everything has to stop while memory is copied.",
        },
      ],
      tags: ["partitioning", "compaction"],
    },
    {
      id: "os-mem-n1",
      subtopic: "Numericals",
      type: "numerical",
      importance: "high",
      question:
        "Allocate four processes to five memory blocks using first fit, best fit and worst fit. Which strategy places them all?",
      short:
        "Only best fit places all four. First fit and worst fit both leave P4 unallocated.",
      given: {
        head: ["", "Sizes (in order)"],
        rows: [
          ["Memory blocks", "100 K · 500 K · 200 K · 300 K · 600 K"],
          ["Processes", "P1 212 K · P2 417 K · P3 112 K · P4 426 K"],
        ],
      },
      find: ["Placement under each strategy", "Which process fails to fit", "Total internal fragmentation"],
      solution: [
        {
          note: "**State the model.** This assumes **one process per block** — a block, once used, is not re-subdivided for a second process. That is the fixed-partition reading, and it is the one your notes use. Under dynamic holes, where the remainder of a block stays available, the answers differ. Say which model you are using.",
        },
        { p: "**First fit** — take the first block large enough, scanning from the start." },
        {
          table: {
            head: ["Process", "Scans", "Placed in", "Internal fragmentation"],
            rows: [
              ["P1 (212 K)", "100 ✗ → 500 ✓", "500 K", "288 K"],
              ["P2 (417 K)", "100 ✗ → 200 ✗ → 300 ✗ → 600 ✓", "600 K", "183 K"],
              ["P3 (112 K)", "100 ✗ → 200 ✓", "200 K", "88 K"],
              ["P4 (426 K)", "only 100 K and 300 K left", "**not allocated**", "—"],
            ],
          },
        },
        { p: "Total internal fragmentation = 288 + 183 + 88 = **559 K**, and P4 does not fit." },
        { p: "**Best fit** — take the smallest block that is still large enough." },
        {
          table: {
            head: ["Process", "Candidates", "Placed in", "Internal fragmentation"],
            rows: [
              ["P1 (212 K)", "500, 300, 600 → smallest is 300", "300 K", "88 K"],
              ["P2 (417 K)", "500, 600 → smallest is 500", "500 K", "83 K"],
              ["P3 (112 K)", "200, 600 → smallest is 200", "200 K", "88 K"],
              ["P4 (426 K)", "600 is the only one left that fits", "600 K", "174 K"],
            ],
          },
        },
        {
          p: "Total internal fragmentation = 88 + 83 + 88 + 174 = **433 K**, and **all four processes fit**.",
        },
        { p: "**Worst fit** — take the largest block available." },
        {
          table: {
            head: ["Process", "Placed in", "Internal fragmentation"],
            rows: [
              ["P1 (212 K)", "600 K (largest)", "388 K"],
              ["P2 (417 K)", "500 K", "83 K"],
              ["P3 (112 K)", "300 K", "188 K"],
              ["P4 (426 K)", "**not allocated** — only 100 K and 200 K left", "—"],
            ],
          },
        },
        { p: "Total internal fragmentation = **659 K**, and P4 does not fit." },
        {
          table: {
            head: ["Strategy", "Processes placed", "Internal fragmentation"],
            rows: [
              ["First fit", "3 of 4", "559 K"],
              ["**Best fit**", "**4 of 4**", "**433 K**"],
              ["Worst fit", "3 of 4", "659 K"],
            ],
          },
        },
        {
          note: "Best fit wins here, and it does **not** win in general. It leaves behind the smallest possible leftover each time, which over a long run produces a lot of slivers too small for anything. First fit is usually faster and in practice about as good, which is why real allocators tend to use it.",
        },
      ],
      tip: "Give the caveat. Answering 'best fit, and here is why that is not a general rule' is worth far more than the arithmetic alone.",
      tags: ["first fit", "best fit", "worst fit", "numerical"],
    },
    {
      id: "os-mem-05",
      subtopic: "Paging",
      type: "conceptual",
      importance: "high",
      question: "What is paging?",
      short:
        "Split physical memory into fixed-size frames and the process into equal-size pages. A page table maps one to the other.",
      answer: [
        {
          ul: [
            "**Frames** — physical memory divided into fixed-size blocks.",
            "**Pages** — the process's logical memory divided into blocks of the *same* size.",
            "**Page table** — one per process, mapping each page to the frame holding it.",
          ],
        },
        {
          p: "Because any page can go in any free frame, a process no longer needs one contiguous run of memory. That single fact **eliminates external fragmentation entirely**.",
        },
        {
          formula: [
            { name: "Page size", expr: "2ⁿ bytes", note: "always a power of two, so the split is bit slicing" },
            { name: "Page number", expr: "⌊ logical address ÷ page size ⌋" },
            { name: "Offset", expr: "logical address mod page size" },
          ],
        },
        {
          note: "Page size is a power of two so the CPU can split an address by **taking bits**, not by dividing. A division on every memory access would be unthinkable.",
        },
      ],
      tags: ["paging", "page table", "frames"],
    },
    {
      id: "os-mem-06",
      subtopic: "Paging",
      type: "how",
      importance: "high",
      question: "How does address translation work under paging?",
      short:
        "Split the address into page number and offset; look the page number up in the page table; replace it with the frame number. The offset never changes.",
      answer: [
        { diagram: "paging-translation" },
        {
          ol: [
            "The CPU produces a logical address.",
            "The high bits are the **page number** p, the low bits the **offset** d.",
            "p indexes the page table, which yields the **frame number** f.",
            "The physical address is f concatenated with d — **the offset is copied across untouched**.",
          ],
        },
        {
          note: "The offset is unchanged because pages and frames are the same size. A byte 755 into page 2 is byte 755 into whichever frame holds it. That is why only the top part of the address is ever looked up.",
        },
        {
          p: "Two registers support this: **PTBR** (page table base register) points at the current process's page table, and **PTLR** (page table length register) holds its size, so an out-of-range page number traps.",
        },
      ],
      tags: ["address translation", "paging"],
    },
    {
      id: "os-mem-n2",
      subtopic: "Numericals",
      type: "numerical",
      importance: "high",
      question: "Translate logical address 0x0AF3 to a physical address.",
      short: "Page 2, offset 0x2F3 → frame 5 → physical address 0x16F3 (5875).",
      given: {
        head: ["", "Value"],
        rows: [
          ["Logical address space", "16 KB = 2¹⁴ → 14-bit logical address"],
          ["Page size", "1 KB = 2¹⁰ → 10-bit offset, so 4 bits of page number"],
          ["Physical memory", "32 KB = 2¹⁵ → 5-bit frame number"],
          ["Page table", "page 0→6, 1→1, **2→5**, 3→13, 4→8, 5→3, 6→0, 7→7, 8→4"],
          ["Logical address", "0x0AF3"],
        ],
      },
      find: ["Page number", "Offset", "Frame number", "Physical address"],
      solution: [
        { p: "**Step 1 — work out the field widths.**" },
        {
          formula: [
            { name: "Offset bits", expr: "log₂(page size) = log₂(1024) = 10" },
            { name: "Page number bits", expr: "14 − 10 = 4" },
            { name: "Frame number bits", expr: "log₂(32 KB ÷ 1 KB) = log₂(32) = 5" },
          ],
        },
        { p: "**Step 2 — split the address.** 0x0AF3 = 2803 in decimal, which is 14 bits: `10 1011 1100 11`." },
        {
          table: {
            head: ["Field", "Bits", "Value"],
            rows: [
              ["Page number p", "top 4", "`0010` = **2**"],
              ["Offset d", "bottom 10", "`10 1111 0011` = 755 = **0x2F3**"],
            ],
          },
        },
        { p: "Check it arithmetically: 2803 ÷ 1024 = 2 remainder 755. ✓" },
        { p: "**Step 3 — look up the frame.** Page table entry 2 → frame **5**." },
        { p: "**Step 4 — assemble the physical address.**" },
        {
          formula: [
            { name: "Physical address", expr: "(frame × page size) + offset" },
            { name: "Here", expr: "(5 × 1024) + 755 = 5120 + 755 = 5875 = 0x16F3" },
          ],
        },
        {
          note: "Your notes set this question with the address **0x2AF3** and a 14-bit address space, which do not fit together: 0x2AF3 needs 14 bits and gives page **10**, not page 2, and their working then shows a 12-bit field labelled \"offset (10-bit)\". With 0x0AF3 their own answer — page 2 → frame 5 — comes out correctly, so the address is what was wrong, not the method.",
          tone: "warn",
        },
      ],
      tip: "Always compute the field widths first and write them down. Nearly every mistake in these questions is a miscounted bit, not a wrong lookup.",
      tags: ["address translation", "paging", "numerical"],
    },
    {
      id: "os-mem-n3",
      subtopic: "Numericals",
      type: "numerical",
      importance: "med",
      question: "With 1 KB pages, what are the page number and offset for logical address 3500?",
      short: "Page 3, offset 428.",
      given: {
        head: ["", "Value"],
        rows: [
          ["Page size", "1 KB = 1024 bytes"],
          ["Logical address", "3500"],
        ],
      },
      find: ["Page number", "Offset"],
      solution: [
        {
          formula: [
            { name: "Page number", expr: "⌊ 3500 ÷ 1024 ⌋ = 3" },
            { name: "Offset", expr: "3500 mod 1024 = 3500 − 3072 = 428" },
          ],
        },
        { p: "So logical address 3500 is byte **428** of page **3**." },
        {
          note: "Your notes give offset **452** for this. 3 × 1024 = 3072 and 3500 − 3072 = **428**. The page number is right; the remainder is not.",
          tone: "warn",
        },
      ],
      tags: ["paging", "numerical"],
    },
    {
      id: "os-mem-07",
      subtopic: "TLB",
      type: "how",
      importance: "high",
      question: "What is the TLB and why is it needed?",
      short:
        "A small fast cache of recent page-table entries. Without it every memory access would cost two — one to read the page table, one for the data.",
      answer: [
        {
          p: "Paging has a cost that is easy to miss: the page table is **in memory**, so translating an address means a memory access, and then you still have to do the one you wanted. Every access costs two.",
        },
        { diagram: "tlb-lookup" },
        {
          ul: [
            "**TLB hit** — the mapping is in the TLB, so the frame number comes back at cache speed and only the data access touches memory.",
            "**TLB miss** — walk the page table in memory, use the result, and insert it into the TLB for next time.",
          ],
        },
        {
          formula: [
            {
              name: "Effective access time",
              expr: "EAT = h × (t_TLB + t_mem) + (1 − h) × (t_TLB + 2 × t_mem)",
              note: "h = hit ratio, t_mem = one memory access",
            },
          ],
        },
        {
          note: "TLB hit rates of 98–99% are normal, because programs have strong **locality** — the same few pages are used over and over. A tiny cache of 64 entries can therefore remove almost the entire cost of paging.",
        },
        {
          p: "This is also the hidden cost of a context switch: the TLB holds one process's translations, so switching means flushing it (or tagging entries with an address-space id) and taking misses until it refills.",
        },
      ],
      tip: "Connect the TLB back to context switching. That link is what makes both answers sound joined up rather than memorised separately.",
      tags: ["tlb", "cache", "locality"],
    },
    {
      id: "os-mem-08",
      subtopic: "Page tables",
      type: "comparison",
      importance: "med",
      question: "Why multilevel paging, and what is an inverted page table?",
      short:
        "A flat page table for a 32-bit space is 4 MB per process. Multilevel paging only keeps the parts in use; an inverted table keeps one table for the whole machine.",
      answer: [
        {
          p: "**The problem.** A 32-bit address space with 4 KB pages has 2²⁰ pages. At 4 bytes per entry that is a **4 MB page table per process** — which must itself be in memory, for every process, most of it never used.",
        },
        {
          table: {
            head: ["", "Multilevel paging", "Inverted page table"],
            rows: [
              ["Structure", "A page directory pointing at page tables", "One global table, one entry per physical frame"],
              ["Size scales with", "Address space actually used", "Physical memory size"],
              ["Lookup cost", "One memory access per level", "A search or hash — slower"],
              ["Entry holds", "Frame number", "Process id + page number"],
              ["Per process?", "Yes", "No — one for the whole system"],
            ],
          },
        },
        {
          p: "**Multilevel** wins because programs use a tiny, clustered fraction of their address space: only the directory and the handful of second-level tables that are actually populated need to exist. The cost is one extra memory access per level — which is exactly what the TLB hides.",
        },
        {
          note: "The inverted table solves the size problem completely — its size depends on the RAM you have, not on how many processes are running — and creates a lookup problem, because you can no longer index straight into it by page number. Hashing is the usual answer.",
        },
      ],
      tags: ["multilevel paging", "inverted page table"],
    },
    {
      id: "os-mem-09",
      subtopic: "Segmentation",
      type: "comparison",
      importance: "high",
      question: "Paging vs segmentation?",
      short:
        "Pages are fixed-size and invisible to the programmer; segments are variable-size and correspond to code, stack, heap and data.",
      answer: [
        {
          table: {
            head: ["", "Paging", "Segmentation"],
            rows: [
              ["Unit", "Fixed-size page", "Variable-size logical segment"],
              ["Divided by", "The hardware", "The program's own structure"],
              ["Address", "⟨page number, offset⟩", "⟨segment number, offset⟩"],
              ["Table entry", "Frame number", "Base, limit, protection"],
              ["Fragmentation", "Internal", "External"],
              ["Visible to the programmer", "No", "Yes"],
              ["Protection and sharing", "Per page — arbitrary boundaries", "Per segment — meaningful boundaries"],
            ],
          },
        },
        { diagram: "segmentation" },
        {
          p: "A segmented address is checked as well as translated: if `offset ≥ limit[s]`, the hardware raises a **segmentation fault**. That check is possible because a segment is a meaningful unit — you cannot ask 'is this offset past the end of the array' when the unit is an arbitrary 4 KB page.",
        },
        {
          note: "**Segmented paging** combines them: divide the program into segments, then divide each segment into pages. You get segmentation's logical protection with paging's freedom from external fragmentation, at the cost of two lookups. This is what x86 has always done.",
        },
      ],
      tags: ["paging", "segmentation", "comparison"],
    },
    {
      id: "os-mem-n4",
      subtopic: "Numericals",
      type: "numerical",
      importance: "med",
      question: "Translate these segmented addresses, or say which one faults.",
      short: "⟨2, 450⟩ → 5450. ⟨1, 300⟩ → 3300. ⟨1, 900⟩ → segmentation fault.",
      given: {
        head: ["Segment", "Base", "Limit", "Protection"],
        rows: [
          ["0", "1000", "400", "R–X"],
          ["1", "3000", "800", "RW–"],
          ["2", "5000", "600", "RW–"],
          ["3", "7000", "300", "R––"],
        ],
      },
      find: ["Physical address for ⟨2, 450⟩, ⟨1, 300⟩ and ⟨1, 900⟩"],
      solution: [
        {
          formula: [
            { name: "Validity check", expr: "offset d < limit[s]" },
            { name: "Physical address", expr: "base[s] + d" },
          ],
        },
        {
          table: {
            head: ["Address", "Limit check", "Result"],
            rows: [
              ["⟨2, 450⟩", "450 < 600 ✓", "5000 + 450 = **5450**"],
              ["⟨1, 300⟩", "300 < 800 ✓", "3000 + 300 = **3300**"],
              ["⟨1, 900⟩", "900 > 800 ✗", "**Segmentation fault**"],
            ],
          },
        },
        {
          p: "Note that ⟨1, 900⟩ names an address, 3900, that exists perfectly well in physical memory — it is simply inside a **different** segment. The limit check is what turns a valid-looking address into a trap, and it is why segmentation gives meaningful protection.",
        },
        {
          note: "These three match your notes exactly. The segmentation worked examples are among the ones that check out.",
        },
      ],
      tags: ["segmentation", "numerical"],
    },
    {
      id: "os-mem-10",
      subtopic: "Extras",
      type: "definition",
      importance: "low",
      question: "What are swapping, overlays and compaction?",
      short:
        "Swapping moves whole processes to disk; overlays were the manual predecessor of virtual memory; compaction shuffles memory to merge free holes.",
      answer: [
        {
          ul: [
            "**Swapping** — move an inactive process out to a swap area on disk to free RAM, and bring it back when needed. Increases the degree of multiprogramming; slow, because disks are slow.",
            "**Overlays** — a program split into mutually exclusive modules, only one of which is loaded at a time. The **programmer** decided the split. This is what people did before virtual memory existed, and it is obsolete for exactly that reason.",
            "**Compaction** — shift all allocated blocks to one end so the free space merges into one large hole. Cures external fragmentation; costs a full memory copy with everything stopped.",
          ],
        },
        {
          note: "Overlays are worth knowing precisely because virtual memory replaced them: demand paging does the same job automatically, at page granularity, without the programmer deciding anything.",
        },
      ],
      tags: ["swapping", "overlay", "compaction"],
    },
    {
      id: "os-mem-m1",
      subtopic: "Quick check",
      type: "mcq",
      importance: "med",
      question: "Paging eliminates which kind of fragmentation?",
      options: ["Internal", "External", "Both", "Neither"],
      correct: 1,
      answer: [
        {
          p: "External only. Any page fits any frame, so there are no unusable gaps — but the last page of a process is rarely full, which is internal fragmentation.",
        },
      ],
      tags: ["mcq", "paging", "fragmentation"],
    },
    {
      id: "os-mem-m2",
      subtopic: "Quick check",
      type: "mcq",
      importance: "med",
      question: "With 4 KB pages, how many bits of a logical address are the offset?",
      options: ["8", "10", "12", "16"],
      correct: 2,
      answer: [{ p: "12, because 4 KB = 4096 = 2¹². The remaining bits are the page number." }],
      tags: ["mcq", "paging"],
    },
    {
      id: "os-mem-m3",
      subtopic: "Quick check",
      type: "mcq",
      importance: "med",
      question: "The MMU translates:",
      options: [
        "Physical addresses to logical addresses",
        "Logical addresses to physical addresses",
        "Page numbers to page sizes",
        "Virtual memory to swap space",
      ],
      correct: 1,
      answer: [
        { p: "Logical to physical, on every memory access, using the current process's page table." },
      ],
      tags: ["mcq", "mmu"],
    },
  ],
};
